### ISSUE TITLE
Nil value for Country Code

### ISSUE THREAD

**Issue by danilotat** [xexpanderx/Conky-themes#1]
Hello, 
Can't figure to make working this theme. I've edit the .lua file with this settings

`api_key = "my_api_key"
city = 3171456
country_code = "IT"`

It keeps me firing this error on terminal

`conky: desktop window (800030) is subwindow of root window (2fe)
conky: window type - normal
conky: drawing to created window (0x3a00002)
conky: drawing to double buffer
conky: llua_do_call: function conky_start_widgets execution failed: settings.lua:86: attempt to concatenate global 'country_code' (a nil value)
`

**Comment by xexpanderx** [comment]
Hi!

Thank you for reporting this. Unfortunately, long city names with "spaces" was not supported. I fixed this, try it again but instead of "city code", type in the name of your city "Provincia di Parma".

**Comment by danilotat** [comment]
Thanks, just downloaded new version but seems that another error comes out. 
`conky: llua_do_call: function conky_start_widgets execution failed: settings.lua:97: bad argument #2 to 'format' (number expected, got string)`

**Comment by xexpanderx** [comment]
Some errors are printed out during the initial startup of conky. If it is still not working, could you please provide your "settings.lua"?

**Comment by danilotat** [comment]
I've fixed that by just deleting the 97th line of `settings.lua`. 
Output of `openweather.py`while launched with this parameters (referring to 96th line):
`temperature = conky_parse("${exec ./openweather.py --get_temp_c --api_key " .. api_key .. " --city " .. "\"" .. city .. "\"" .. " --ccode " .. country_code .. "}") ` gives already a number as output, so there's no need for conversion in the next line.

**Comment by xexpanderx** [comment]
Glad you solved it! However, that string will be converted to non-decimals. Gonna look-over the code.
