### ISSUE TITLE
[Question from noob] Getting lua cairo error as it's not found 

### ISSUE THREAD

**Issue by cockadoolie** [xexpanderx/Conky-themes#4]
Hi Xexpanderx!

I appreciate that youu are publishing your quality artwork on github, making to us available at the same time!

I'm running Debian and experimenting with your Conky-Weather setup. I've managed to configure settings.lua part what you suggested to edit. 

When I execute start_weather.sh, I get following message:

> conky: llua_load: settings.lua:19: module 'cairo' not found:
> 	no field package.preload['cairo']
> 	no file './cairo.lua'
> 	no file '/usr/local/share/lua/5.1/cairo.lua'
> 	no file '/usr/local/share/lua/5.1/cairo/init.lua'
> 	no file '/usr/local/lib/lua/5.1/cairo.lua'
> 	no file '/usr/local/lib/lua/5.1/cairo/init.lua'
> 	no file '/usr/share/lua/5.1/cairo.lua'
> 	no file '/usr/share/lua/5.1/cairo/init.lua'
> 	no file '/usr/lib/conky/libcairo.so'
> 	no file './cairo.so'
> 	no file '/usr/local/lib/lua/5.1/cairo.so'
> 	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/cairo.so'
> 	no file '/usr/lib/lua/5.1/cairo.so'
> 	no file '/usr/local/lib/lua/5.1/loadall.so
> 

I've done a research but not sure what cairo package is actually required here.

Appreciate any help.

**Comment by xexpanderx** [comment]
Hey and thank you!

It looks like you do not have cairo installed for lua. Have you tried the conky-all package like:

`sudo apt install conky-all`

**Comment by cockadoolie** [comment]
Thanks! Yeah, that's solved this particular issue issue. 

Launching it afterwards, it started to scream about some other discrepancies (I did not modify your openweather.py and all files is located at /home/myusername/.conky/Conky-Weather/): 

> Traceback (most recent call last):
  File "./openweather.py", line 29, in <module>
    process(args)
  File "./openweather.py", line 9, in process
    weather_details = owm.weather_at_place(args.city[0] + ',' + args.ccode[0])
AttributeError: 'OWM' object has no attribute 'weather_at_place'
conky: llua_do_call: function conky_start_widgets execution failed: settings.lua:98: bad argument #2

**Comment by xexpanderx** [comment]
Oh, thanks. That is actually a bug, it is using an older version of pyowm. I will update it.

**Comment by cockadoolie** [comment]
Thank you for your support. Hopefully, I'll get there once to know how to update such beast so I can straight come to you with a solution

**Comment by xexpanderx** [comment]
Hey, I updated the scripts. Can you do a new clone and retry?

**Comment by cockadoolie** [comment]
Conky itself works without errors now, thank you for that. It shows me the icon without the actual temperature:

![image](https://user-images.githubusercontent.com/76849627/104086083-ebb26680-5254-11eb-8ac3-49e61356f547.png)

This is how my lua settings looks like:

> -- ###Openweather settings###
api_key = "myownapikey_gathered 2 days ago from free subscription"
city = "Budapest"
country_code = "HU"
-- ###Colors###
HTML_circle = "#232323"
HTML_border = "#000000"
HTML_text = "#FFFFFF"
transparency = 1.0
transparency_border = 1.0
transparency_text = 1.0
transparency_weather_icon = 0.6
-- ###Font sizes###
Roboto = 9
Roboto = 24
Roboto = 12

Thanks for looking into it.

**Comment by xexpanderx** [comment]
Ok, thats... interesting. I did another update to force the text and the icon on top-layer. Please, re-clone and try again.

**Comment by xexpanderx** [comment]
Did another update to force the text and circle to show up on top-layer. Re-clone and test now. It works for me.

**Comment by xexpanderx** [comment]
Also make sure to wait 15 seconds until it does a fully refresh after you started it.

**Comment by cockadoolie** [comment]
Thanks for the effort! I'm still getinng the weather icon  without the text. May be it gets affected by my my api key or system setup. Here is what I get once I run the script (but I guess that's normal):

> conky: desktop window (1400003) is subwindow of root window (19f)
conky: window type - normal
conky: drawing to created window (0x7400002)
conky: drawing to double buffer

Conky looks the same as at my post above.

**Comment by xexpanderx** [comment]
Which DE/WM are you running, and which Debian version (stable, testing..)?

**Comment by xexpanderx** [comment]
Also, which conky version are you running?

**Comment by cockadoolie** [comment]
Sharing the data as below:

- XFCE 4.12, Debian stable with backports

- conky 1.10.8 compiled Tue May 15 07:41:15 UTC 2018 for Linux 4.9.0-6-amd64 x86_64

**Comment by xexpanderx** [comment]
Ok thanks. I am clueless, we use the same version of Conky. I also tried it in Xfce. I tested this on another laptop, could not replicate the problem.

Can you try with different values in the conky_config regarding the `own_window_type = 'normal'`. You can set own_window_type to folliwing values:
normal, desktop, dock, panel or override

One other thing you can try yourself is to comment out the lines containing `cairo_set_operator(cr, CAIRO_OPERATOR_SOURCE)`  and `cairo_set_operator(cr, CAIRO_OPERATOR_OVER)`. Like this (in settings.lua):

`--cairo_set_operator(cr, CAIRO_OPERATOR_SOURCE)`
`--cairo_set_operator(cr, CAIRO_OPERATOR_OVER)`

I am sorry, I am not much of a help since I cannot reproduce this error.

**Comment by cockadoolie** [comment]
Thanks for your help provided so far. I'll experiment and report back if I've managed to get it fully running on my machine. 

Thank you once again.
