### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Aneeqasif** [xexpanderx/Conky-themes#5]
i did as y say but it didnt worked on my system ,manjaro kde :( what should i do (conky weather theme)

output of command:
`no field package.preload['cairo']
        no file '/usr/share/lua/5.4/cairo.lua'
        no file '/usr/share/lua/5.4/cairo/init.lua'
        no file '/usr/lib/lua/5.4/cairo.lua'
        no file '/usr/lib/lua/5.4/cairo/init.lua'
        no file './cairo.lua'
        no file './cairo/init.lua'
        no file '/usr/lib/conky/libcairo.so'
        no file '/usr/lib/lua/5.4/cairo.so'
        no file '/usr/lib/lua/5.4/loadall.so'
        no file './cairo.so'
conky: Invalid value 'conky' for setting 'own_window_type'. Valid values are: 'normal', 'dock', 'panel', 'desktop', 'override'.
conky: desktop window (2400015) is subwindow of root window (136)
conky: window type - normal
conky: drawing to created window (0x7c00002)
conky: drawing to double buffer
conky: llua_do_call: function conky_start_widgets execution failed: attempt to call a nil value
conky: llua_do_call: function conky_start_widgets execution failed: attempt to call a nil value
conky: llua_do_call: function conky_start_widgets execution failed: attempt to call a nil value
conky: llua_do_call: function conky_start_widgets execution failed: attempt to call a nil value
conky: llua_do_call: function conky_start_widgets execution failed: attempt to call a nil value
conky: llua_do_call: function conky_start_widgets execution failed: attempt to call a nil value

`

**Comment by xexpanderx** [comment]
You dont have Conky with Cairo installed. You are also running Lua 5.4, which I do not support (it may work though).
