### ISSUE TITLE
[Conky revisited 2] CPU stats aren't working 

### ISSUE THREAD

**Issue by devqueue** [xexpanderx/Conky-themes#7]
I am using conky on Kali Linux.  It's working fine but the CPU stat shows 0% all the time even under heavy load. Earlier the battery percentage wasn't working but I opened the `settings.lua` file changed `BAT0` to `BAT1` and it worked fine. But I can't find anything as such for the CPU stat. Also, I noticed CPU_NUMBER was set to 4 and I have 8 cores, Will the hard coded value be a problem?

**Comment by xexpanderx** [comment]
It is weird it shows 0%, but yes, you should change cpu_number to 8.

Which CPU do you have btw?

**Comment by devqueue** [comment]
Yes I did but there was no change. I still see the cpu percentage as 0% 
I have a ryzen 7 5700u. Running on a Lenovo flex 5. 
Is there anything I can change in the `draw_cpu` function. In not really familiar with Lua but I assume anything I change has to be in the conky_parse() 
```
conky_parse('${cpu cpu' .. tostring(i) .. '}'))
```
Or maybe here 
```
cairo_show_text(cr, conky_parse('${cpu cpu0}' .. "%"))
```

Can you please suggest something?

**Comment by devqueue** [comment]
Here's a screenshot that might illustrate the issue 

![Screenshot_2021-08-31_11-53-46](https://user-images.githubusercontent.com/55657198/131473385-bf90853d-1c48-4927-b949-40b9e5ef14d3.png)

**Comment by xexpanderx** [comment]
Hey, can you try using a "normal" config file for conky, try with the `cpu cpu0`? Do you get anything?

Some questions:

- Which conky version do you use?
- What distro?

Again, try with a very simple conky showing only CPU.

**Comment by devqueue** [comment]
**1. Conky version**
```
conky 1.11.6 compiled 2020-08-17 for Linux x86_64

```
I'm running Kali-Linux on wsl2 using XRDP remote desktop for the GUI

**Comment by xexpanderx** [comment]
Sounds like this is a Conky issue, not a configuration issue. Please contact Conky developers.

Closing this.

**Comment by devqueue** [comment]
okay thanks

**Comment by elightcap** [comment]
@devqueue did you ever find a solution to this? im running into the same issue

**Comment by devqueue** [comment]
No i couldn't I just ended up removing the cpu and ram stat lines from the config.

**Comment by abraham-lincoln-okaalo** [comment]
> Sounds like this is a Conky issue, not a configuration issue. Please contact Conky developers.
> 
> Closing this.

I doubt that this is an issue with Conky. 
Conky Circle Horizontal and Conky Circle Vertical display the CPU Total Usage well.
Conky Square Horizontal and Conky Square Vertical do not display the CPU total usage. 
[product: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz] [Kali GNU/Linux Rolling(2021.4)]
These work well on Arch though.
Still troubleshooting.

**Comment by xexpanderx** [comment]
Ok, interesting. Can you try change line 316 in "settings.lua" for Conky Square Horizontal to this:
`cairo_show_text(cr, conky_parse('${cpu cpu0}') .. "%")`

Will that make any difference?

**Comment by abraham-lincoln-okaalo** [comment]
> Ok, interesting. Can you try change line 316 in "settings.lua" for Conky Square Horizontal to this: `cairo_show_text(cr, conky_parse('${cpu cpu0}') .. "%")`
> 
> Will that make any difference?

Thanks for the qr.
Tried this, unfortunately, there's no change.

**Comment by xexpanderx** [comment]
Still showing "0"? Then it does not make sense, since it is a very basic command and should work. This looks like Conky issue to me.

Does `${cpu cpu0}` work in a normal conky configuration?

**Comment by abraham-lincoln-okaalo** [comment]
> Still showing "0"? Then it does not make sense, since it is a very basic command and should work. This looks like Conky issue to me.
> 
> Does `${cpu cpu0}` work in a normal conky configuration?

Okay. Hopefully I can get around that. 
Yes it does.

**Comment by TanawatJukmongkol** [comment]
This is what I worked out (I have the same issue): Basically, it doesn't update the cpu info to save on battery. You have to execute `${cpu cpu0}` in the `conky.text = [[]]` first, then `conky_parse('${cpu cpu0}')` will start working, though it will look ugly. They should add a method / expose the variable that prevent updating the CPU stats somewhere to allow reading and updating the CPU stats.
